sudo: false

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change
  slack: wpsyntex:LIVXuF2AQ9HXNm93zkWtR8fw

branches:
  only:
    - master
    - travis

matrix:
  include:
  - name: PHPCS
    php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 PHPCS=1
  - name: PHP Nightly
    php: nightly
    env: WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - |
    if [[ "$PHPCS" != "1" ]]; then
      bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      bash tests/bin/install-plugins.sh
    fi
  - composer install
script:
  - |
    if [[ "$PHPCS" == "1" ]]; then
      vendor/bin/phpcs -s --extensions=php,js .
    else
      vendor/bin/phpunit
    fi
